### ISSUE TITLE
ionic state restore fails for new project

### ISSUE THREAD

**Issue by patrickjpena** [natevecc/ionic-angular-cli-starter#1]
You cannot run any state commands on a project that is not an Ionic project.
Try adding an ionic.project file or running ionic start to get an application to save or restore (CLI v2.0.0-beta.17)

Your system information:

Cordova CLI: You have been opted out of telemetry. To change this, run: cordova telemetry on.
6.2.0

Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic CLI Version: 2.0.0-beta.17
Ionic App Lib Version: 2.0.0-beta.8
ios-deploy version: Not installed
ios-sim version: 5.0.6 
OS: Mac OS X El Capitan
Node Version: v5.7.0
Xcode version: Xcode 7.3.1 Build version 7D1014

**Comment by natevecc** [comment]
Fixed by this [commit](https://github.com/natevecc/ionic-angular-cli-starter/commit/cd855a2fef3f822f9adff11f19c878fdfd17a2c4)
